server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: my-redis
#  profiles:
#    active: dev
  redis:
    host: 192.168.2.162
    password: 123456
    database: 1
#redisson配置
  redisson:
    host: 192.168.2.162
    port: 6379
    password: 123456
    database: 1